package modelo;
// Generated 06/06/2020 11:48:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String producto;
     private Integer precio;
     private Set promoproductos = new HashSet(0);

    public Producto() {
    }

    public Producto(String producto, Integer precio, Set promoproductos) {
       this.producto = producto;
       this.precio = precio;
       this.promoproductos = promoproductos;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }
    public Set getPromoproductos() {
        return this.promoproductos;
    }
    
    public void setPromoproductos(Set promoproductos) {
        this.promoproductos = promoproductos;
    }

    @Override
    public String toString() {
        return "Producto{" + "idProducto=" + idProducto + ", producto=" + producto + ", precio=" + precio + ", promoproductos=" + promoproductos + '}';
    }

    


}


